platform :ios, '11.0'
use_frameworks!

target 'VKclient' do
	pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
end
